baseURL: 'https://rmi.labs.cip.fun/rmi_2023'
title: Romanian Master of Informatics 2023

languageCode: en-us
enableRobotsTXT: true
canonifyURLs: true
theme: rms-theme
staticDir:
  - static/
  - favicon/
disableKinds:
  - taxonomy
  - taxonomyTerm

minify:
  tdewolff:
    html:
      keepWhitespace: false

params:
  logo: /assets/logo.svg
  heading: 'October 11th - October 14th, 2023'
  author: Colegiul Național de Informatică "Tudor Vianu"
  author_url: 'https://lbi.ro/'
  useSlider: false
  baseColor: '#1a494c'
  fontFamily: '"Space Grotesk", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
  oldHeader: false
  finished: false

menu:
  main:
    - identifier: root
      name: RMI 2023
      title: RMI 2023
      weight: 1

    - identifier: organisation
      name: RMI Organisation
      title: RMI Organisation
      weight: 2

    - identifier: contest
      name: RMI Contest
      title: RMI Contest
      weight: 3

    - identifier: info
      name: General Information
      title: General Information
      weight: 4

    - url: 'https://en.wikipedia.org/wiki/Romania'
      name: About Romania
      title: About Romania
      parent: info
      weight: 1

    - url: 'https://en.wikipedia.org/wiki/Bucharest'
      name: About Bucharest
      title: About Bucharest
      parent: info
      weight: 2

    - url: 'http://www.romaniatourism.com/'
      name: Tourist Guide
      title: Tourist Guide
      parent: info
      weight: 3

markup:
  goldmark:
    renderer:
      unsafe: true
